server:
  port: 19000
spring:
  application:
    name: bz-invite
  datasource:
    url: jdbc:mysql://localhost:3306/bz_invite
    username: root
    password: zqh123
    driver-class-name: com.mysql.cj.jdbc.Driver
    servlet:
      multipart:
        max-file-size: 2MB
        max-request-size: 5MB
  jackson:
    default-property-inclusion: non_null
#  redis:
#    port: 6379
#    url: localhost
knife4j:
  basic:
    enable: true
    username: test
    password: 124
  enable: true
#logging:
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: t_